
spring:
  datasource:
    url: jdbc:mariadb://192.168.219.100:43306/winemine
    driver-class-name: org.mariadb.jdbc.Driver
    username: user
    password: 12345


  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
